ClienteObligatorioP3/Controllers/AuthController.cs
using ClienteObligatorioP3.Models;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace ClienteObligatorioP3.Controllers
{
    public class AuthController : Controller
    {
        private HttpClient _httpClient;
        public AuthController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://obligatoriowebapip3.azurewebsites.net/");
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LoginAsync(DTOLogin login)
        {
            var json = JsonSerializer.Serialize(login);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/api/Auth/login", content);
            if (response.IsSuccessStatusCode)
            {
                string result = await response.Content.ReadAsStringAsync();
                var tk = JsonSerializer.Deserialize<TokenResponse>(result, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                HttpContext.Session.SetString("Token", tk.Token);
            }
            else
            {
                string errorMessage = await response.Content.ReadAsStringAsync();
                ViewBag.Error = errorMessage;
                return View();
            }

            return RedirectToAction("Index", "Home"); ;

        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public IActionResult ModificarPass()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ModificarPassAsync(DTOModificarPassword dto)
        {
            string token = HttpContext.Session.GetString("Token");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            try
            {
                var json = JsonSerializer.Serialize(dto);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PutAsync("/api/Password/Modificar", content);

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "Contraseña actualizada correctamente.";
                    return View();
                }
                else
                {
                    string errorMessage = await response.Content.ReadAsStringAsync();
                    ViewBag.Error = errorMessage;
                    return View(dto);
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Ocurrió un error inesperado. Intenta más tarde.";
                return View(dto);
            }
        }



    }
}

ClienteObligatorioP3/Controllers/EnvioController.cs
using ClienteObligatorioP3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace ClienteObligatorioP3.Controllers
{
    public class EnvioController : Controller
    {
        private HttpClient _httpClient;
        public EnvioController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://obligatoriowebapip3.azurewebsites.net/");
        }
        public IActionResult RastrearEnvio()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RastrearEnvioAsync(int numTrack)
        {
            try
            {
                var response = await _httpClient.GetAsync($"/api/Envio/{numTrack}");
                if (response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync();
                    var envios = JsonSerializer.Deserialize<DTOEnvio>(result, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });

                    return View(envios);
                }
                else
                {
                    ViewBag.Mensaje = "Error";
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EnviosUsuarioAsync()
        {

            string token = HttpContext.Session.GetString("Token");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response = await _httpClient.GetAsync("/api/Envio/MisEnvios");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var listaenvios = JsonSerializer.Deserialize<List<DTOEnvio>>(content, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                return View(listaenvios);
            }
            else
            {
                Console.WriteLine($" Error: {response.StatusCode} - {response.ReasonPhrase}");
                ViewBag.Error = "No se pudieron obtener los envíos. Intenta más tarde.";
                return View(new List<DTOEnvio>());
            }


        }

        public async Task<IActionResult> DetalleSeguimientoAsync(int numTracking, List<DTOEnvio> listaEnvios)
        {
            string token = HttpContext.Session.GetString("Token");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            HttpResponseMessage response = await _httpClient.GetAsync($"/api/Envio/{numTracking}");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();

                var envio = JsonSerializer.Deserialize<DTOEnvio>(content, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
                return View(envio.Seguimiento);
            }
            else
            {
                ViewBag.Error = "Error al obtener el detalle del envío. Intenta más tarde.";
                return View(new List<DTOSeguimiento>());
            }

        }

        [HttpGet]
        public IActionResult PorFechas()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PorFechas(DTOEnvioPorFechas dto)
        {
            string token = HttpContext.Session.GetString("Token");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            try
            {
                var json = JsonSerializer.Serialize(dto);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await _httpClient.PostAsync("/api/Envio/PorFechas", content);

                if (response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync();
                    var listaEnvios = JsonSerializer.Deserialize<List<DTOEnvio>>(result, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });

                    ViewBag.Envios = listaEnvios;
                    return View(dto);
                }
                else
                {
                    string errorMessage = await response.Content.ReadAsStringAsync();
                    ViewBag.Error = errorMessage;
                    return View();
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Ocurrió un error inesperado. Intenta más tarde.";
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> BuscarPorComentario(string palabra)
        {
            string token = HttpContext.Session.GetString("Token");
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            try
            {
                var response = await _httpClient.GetAsync($"/api/Envio/PorComentarios?palabra={palabra}");
                if (response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync();
                    var envios = JsonSerializer.Deserialize<List<DTOEnvio>>(result, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                    return View(envios);
                }
                else
                {
                    string error = await response.Content.ReadAsStringAsync();
                    ViewBag.Error = error;
                }
            }
            catch
            {
                ViewBag.Error = "Ocurrió un error inesperado. Intenta más tarde.";
                return View();

            }

            return View();
        }




    }
}

ClienteObligatorioP3/Views/Shared/_Layout.cshtml
@{
    string token = Context.Session.GetString("Token");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClienteObligatorioP3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClienteObligatorioP3.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
    @if (token is not null)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                        🚚 ClienteObligatorioP3
                    </a>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon text-dark"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Envio" asp-action="RastrearEnvio">
                                    🔍 Rastrear Envio
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Envio" asp-action="EnviosUsuario">
                                    📦 Mis Envios
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Envio" asp-action="PorFechas">
                                    🔎 Buscar Envios por Fechas
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Envio" asp-action="BuscarPorComentario">
                                    💬 Buscar Envios por Comentarios
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Auth" asp-action="ModificarPass">
                                    ⚙️ Cambiar Password
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark px-3 py-2 hover-scale" asp-area="" asp-controller="Auth" asp-action="Logout">
                                    🚪 Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

     @* <footer class="border-top footer text-muted">
         <div class="container">
             &copy; 2025 - ClienteObligatorioP3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </div>
     </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>